[project]
# should be the same as the project directory
name = "armor-visibility"
group = "com.diontryban.armor_visibility"
java_version = "21"
gradle_version = "8.12"

[mod]
id = "armor_visibility"
name = "Armor Visibility"
author = "Trikzon"
version = "21.3.1"
license = "LGPL-3.0-or-later"
credits = ""
description = "View your and others' skins through armor"
curseforge_id = "387962"
modrinth_id = "kvPlmCLX"

[common]
minecraft_version = "1.21.3"
minecraft_version_range = "[1.21.3, 1.22)"
# https://projects.neoforged.net/neoforged/neoform
neoform_version = "1.21.3-20241023.131943"
# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
parchment_minecraft_version = "1.21.3"
parchment_version = "2024.12.07"
# https://maven.diontryban.com/#/releases/com/diontryban/ash_api
ash_version = "21.3.0-beta"
gradle_dependencies = """"""

[fabric]
# https://fabricmc.net/develop/
version = "0.114.0+1.21.3"
loader_version = "0.16.14"
loom_version = "1.10-SNAPSHOT"
# https://modrinth.com/mod/modmenu/versions
modmenu_version = "12.0.0"
publish_dependencies = "ash-api"
gradle_dependencies = """"""

[neoforge]
# https://projects.neoforged.net/neoforged/neoforge
version = "21.3.76"
loader_version_range = "[4,)"
# https://projects.neoforged.net/neoforged/moddevgradle
moddevgradle_version = "2.0.88"
publish_dependencies = "ash-api"
gradle_dependencies = """"""
