# IMPORTANT:
# Every field listed here must be added to the expandProps map in
# buildSrc/src/main/goovy/multiloader-common.gradle.

# Project
group=%MDKG_PROJECT_GROUP%
java_version=%MDKG_PROJECT_JAVA_VERSION%

# Mod
mod_id=%MDKG_MOD_ID%
mod_name=%MDKG_MOD_NAME%
mod_author=%MDKG_MOD_AUTHOR%
version=%MDKG_MOD_VERSION%
license=%MDKG_MOD_LICENSE%
credits=%MDKG_MOD_CREDITS%
description=%MDKG_MOD_DESCRIPTION%

# Common
minecraft_version=%MDKG_COMMON_MINECRAFT_VERSION%
minecraft_version_range=%MDKG_COMMON_MINECRAFT_VERSION_RANGE%
neoform_version=%MDKG_COMMON_NEOFORM_VERSION%
parchment_minecraft_version=%MDKG_COMMON_PARCHMENT_MINECRAFT_VERSION%
parchment_version=%MDKG_COMMON_PARCHMENT_VERSION%
ash_version=%MDKG_COMMON_ASH_VERSION%

# Fabric
fabric_version=%MDKG_FABRIC_VERSION%
fabric_loader_version=%MDKG_FABRIC_LOADER_VERSION%
modmenu_version=%MDKG_FABRIC_MODMENU_VERSION%

# NeoForge
neoforge_version=%MDKG_NEOFORGE_VERSION%
neoforge_loader_version_range=%MDKG_NEOFORGE_LOADER_VERSION_RANGE%

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
